version: "3.8"
services:
  app:
    build: .
    depends_on:
      - postgres
    env_file: .env
    environment:
      NODE_PORT: "${NODE_PORT:-8080}"
      ENV: "${ENV:-prod}"
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
      - "9229:9229"
      - "3000:3000"
    volumes:
      - ./:/usr/src/app/
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-root}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-root}"
      POSTGRES_DB: "${POSTGRES_DB:-root}"
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
